### PR TITLE
Reusable blocks header/footer and a bit of fixes

### LINKED ISSUE #726: Repeater in options crashes block
### Describe your bug

Using `Repeater` and `RepeaterItem` crashes the block.

### Steps to Reproduce

Add `Repeater`
Add `RepeaterItem`
Add some option inside `RepeaterItem`

### Expected behavior

Just to work.

### Screenshots, screen recording, code snippet
image

image

### Environment info

_No response_

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

### PR DESCRIPTION
**Pull request by goranalkovic-infinum**
Changes:
- removed `menu` component, as it's not needed anymore
- removed `layout-three-columns` as it's not used anywhere anymore
- added `admin-header-footer-picker` component (renders the settings page)
- updated the default theme logo to the new ES DevKit one
- fixed #726 (bug with Repeater)
- totally revamped theme and plugin setups visually
- theme setup is now fully hands-off and automatic (including `init theme`, `npm install`, `theme activate` and setting up reusable header/footer) 🎉 
- fixed `LinkEditComponent` not clearing properly when there's no text inside in some cases

image

### CODE REVIEW

File: blocks/init/src/Blocks/components/admin-header-footer-picker/admin-header-footer-picker.php [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+		<form action="options.php" method="post">
+			<?php
+			// Output settings fields.
+			settings_fields(ReusableBlocksHeaderFooter::ADMIN_MENU_SLUG);
+
+			// Output settings sections.
+			do_settings_sections(ReusableBlocksHeaderFooter::ADMIN_MENU_SLUG);
+
+			// Render save button.
+			submit_button(__('Save', 'twentythree'));
```
Comment (piqusy) [inline blocks/init/src/Blocks/components/admin-header-footer-picker/admin-header-footer-picker.php:37]: `twentythree` ?

File: setup/create-wp-project/src/basics/command-line.js [hunk 2]
```diff
@@ -41,6 +41,9 @@ const installNodePackage = async (projectPath, packageToInstall) => exec(`cd "${
 const installComposerDependencies = async (projectPath) => exec(`cd "${projectPath}" && composer install --ignore-platform-reqs`);
 const installComposerPackage = async (projectPath, packageToInstall) => exec(`cd "${projectPath}" && composer require ${packageToInstall} --ignore-platform-reqs`);
 const wpCoreDownload = async (projectPath) => exec(`cd "${projectPath}" && wp core download`);
+const wpThemeActivate = async (themeName) => exec(`wp theme activate ${themeName}`);
+const boilerplateThemeInit = async (themeName) => exec(`cd "${themeName}" && wp boilerplate init theme && npm run build`);
+const initReusableHF = async () => exec('wp boilerplate init header-footer');
```
Comment (piqusy) [inline setup/create-wp-project/src/basics/command-line.js:46]: I'd suggest more verbose names for variables 😊

**Review by piqusy — CHANGES_REQUESTED** [review]
Looking goooooood 👏🏼 
I have two suggestions 😊

**Review by iobrado — APPROVED** [review]

**Review by piqusy — APPROVED** [review]

**Review by iruzevic — APPROVED** [review]
